### ISSUE TITLE
concatJsDest?

### ISSUE THREAD

**Issue by HarelM** [AdrienTorris/Angular2TypeScriptASPNETCoreWebApp#1]
Am I missing something or is `concatJsDest` variable is just in use in `gulpfile.js` but not defined in `gulp.config.js`?

**Comment by AdrienTorris** [comment]
You're right, I had some errors in my gulp's configuration file. Thank's you for report it. It was fix with my last commit.

**Comment by HarelM** [comment]
Is there a way to copy the dependencies without duplicate the systemjs code?
I feel that for every dependency added I'll need to do three actions: 
1. Add to npm project json
2. Add to system.js
3. Add to the gulp task (Maybe it's not too much when I look at it this way, but still...)
